SERVER_PORT: 8091
SERVLET_CONTEXT_PATH:
# NON_AUTHENTICATED_PATHS: /actuator/**, /docs/**, /swagger-ui/**

DATASOURCE:
DATASOURCE_USERNAME:
DATASOURCE_PASSWORD:

API_DOCS_ENABLED: true

HIBERNATE_SQL_LOG_LEVEL: DEBUG
HIBERNATE_SQL_BINDER_LOG_LEVEL: TRACE
GET_REQUEST_LOG_LEVEL: DEBUG
REQUEST_RESPONSE_BODY_LOG_LEVEL: DEBUG
